[package]
name = "termite-dmg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.50"
append-only-vec = "0.1.3"
indoc = "2.0.5"
