name: Rust

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
    - name: Build
      run: cargo build --verbose
    - name: Install dependencies
      run: dart pub get
    - name: Run tests
      run: cargo test --verbose
